FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app/

RUN pip install --upgrade pip
RUN pip freeze > requirements.txt

RUN npm install
RUN npm i -D daisyui@latest
RUN python manage.py tailwind install

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
