# Gunakan base image Python
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install dependensi sistem
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Salin semua file ke dalam container
COPY . /app/

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install Tailwind
RUN npm install
RUN npm i -D daisyui@latest
RUN python manage.py tailwind install

# Expose port aplikasi
EXPOSE 8000

# Jalankan perintah untuk memulai server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
